### ISSUE TITLE
Small path issue on MacOS

### ISSUE THREAD

**Issue by Chopium** [rurre/Editor-Screenshot#5]
In the function void TakeScreenshot(),
this line
string screenshotPath = $"{savePath}\\{screenshotName}";

should be 
string screenshotPath = Path.Combine(savePath, screenshotName);

so the path formatting works on MacOS.

**Comment by rurre** [comment]
Will fix, thank you!
________________________________
From: Chopium ***@***.***>
Sent: Saturday, April 13, 2024 9:29:04 PM
To: rurre/Editor-Screenshot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rurre/Editor-Screenshot] Small path issue on MacOS (Issue #5)


In the function void TakeScreenshot(),
this line
string screenshotPath = $"{savePath}\{screenshotName}";

should be
string screenshotPath = Path.Combine(savePath, screenshotName);

so the path formatting works on MacOS.

**Comment by rurre** [comment]
Fixed!
